### ISSUE TITLE
When running the command make deploy-compute

### ISSUE THREAD

**Issue by danielkon96** [rcarmo/azure-k3s-cluster#1]
Hi Rui,

This project looks promising but I ran into an issue when running deploy-compute. My master node does not get created and I get this error when running view-deployment:

"master0           Microsoft.Network/publicIPAddresses               Failed     BadRequest"

I'm not sure what is causing this error and had luck trying to find out but I wanted to inform you.

**Comment by rcarmo** [comment]
you were probably colliding with another cluster - you need to change the names.
